test vboxdrv

diff --git a/vbox-1.4/debian/vbox/DEBIAN/postinst b/vbox-1.4/debian/vbox/DEBIAN/postinst
--- a/vbox-1.4/debian/vbox/DEBIAN/postinst
+++ b/vbox-1.4/debian/vbox/DEBIAN/postinst
@@ -1,3 +1,49 @@
+#!/bin/sh
+# postinst script for vbox
+#
+# see: dh_installdeb(1)
+
+set -e
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see https://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+systemctl  daemon-reload
+
+if [ ! -f /var/log/vbox.log ]
+then
+    touch /var/log/vbox.log
+fi
+
+case "$1" in
+    configure)
+    	# Source debconf library.
+		#. /usr/share/debconf/confmodule
+		#db_get vbox/vmuser
+		#VMUSER="$RET"
+
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
 # Automatically added by dh_systemd_enable
 # This will only remove masks created by d-s-h on package removal.
 deb-systemd-helper unmask vbox.service >/dev/null || true
@@ -36,3 +82,6 @@ else
 	deb-systemd-helper update-state vbox.service >/dev/null || true
 fi
 # End automatically added section
+
+
+exit 0
